@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueCompanyList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueStatusList
UniqueTagList -[hidden]down- UniqueCompanyList
UniqueTagList -[hidden]down- UniqueCompanyList
UniqueStatusList -[hidden]down- UniqueCompanyList

UniqueTagList -right-> "*" Tag
UniqueStatusList -right-> "*" Status
UniqueCompanyList -right-> Company

Company -up-> "*" Tag
Company -up-> "1" Status

Company *--> "1" Name
Company *--> "0..1" Phone
Company *--> "0..1" Email
Company *--> "0..1" Address
Company *--> "1" Remark
@enduml
